name: 17 - 1 custom actions - composite

on:
  workflow_dispatch:


env:
    working-dir: "${{ github.workspace }}/17-custom-actions/react-app"
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ${{ env.working-dir }}
        steps:
            - name: List react-app directory
              run: "pwd"
              shell: bash
            - uses: actions/checkout@v3
            - name: Setup Node and NPM dependencies using custom composite action
              uses: ./.github/actions/composite-cache
              with:
                node-version: "20.x"
                working-dir: "${{ github.workspace }}/17-custom-actions/react-app"
            - name: Test application
              run: npm run test
              shell: bash
            - name: Build application
              run: npm run build
              shell: bash
