name: 17 - 1 custom actions - composite

on:
  workflow_dispatch:

env:
    working-dir: "17-custom-actions/react-app"
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ${{ env.working-dir }}
        steps:
            - uses: actions/checkout@v3
            - name: List react-app directory
              run: |
                echo "Listing contents of react-app directory..." && ls -la
                echo "diretorio de trabalho: ${{ env.working-dir }}"
                echo "pwd: " && pwd
            - name: Setup Node and NPM dependencies using custom composite action
              uses: ./.github/actions/composite-cache
              with:
                node-version: "20.x"
                working-dir: "17-custom-actions/react-app"
            - name: Test application
              run: npm run test
              shell: bash
            - name: Build application
              run: npm run build
              shell: bash
