name: 17 - 2 custom actions - JS Function
run-name: 17 - 2 custom actions - JS | DEBUG
on:
  workflow_dispatch:

jobs:
    dependency-update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Check for dependency updates using custom JavaScript action
              uses: ./.github/actions/js-dependency-update
       