name: 17 - 2 custom actions - JS Function
run-name: 17 - 2 custom actions - JS | BB - ${{ inputs.base-branch }} TB - ${{ inputs.target-branch }} - ${{ inputs.working-dir }}

#settings
#Code and automattions > General
#Allow GitHub Actions to create and approve pull requests

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main
      target-branch:
        type: string
        default: update-dependencies
      worging-dir:
        type: string
        default: 17-custom-actions/react-app

permissions:
  contents: write
  pull-requests: write

jobs:
    dependency-update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Check for dependency updates using custom JavaScript action
              uses: ./.github/actions/js-dependency-update

              with:
                base-branch: ${{ inputs.base-branch }}
                head-branch: ${{ inputs.target-branch }}
                working-directory: ${{ inputs.worging-dir }}
                gh-token: ${{ secrets.GITHUB_TOKEN }}
                #debug: 'true'
       