name: 17 - 3 - custom actions - Dockerfile
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to ping'
        default: 'https://www.google.com'


jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Ping URL
              uses: ./.github/actions/dockerfile-url
              with:
                url: ${{ inputs.url }}